ALTER TABLE website_leads
  ADD COLUMN IF NOT EXISTS nurture_step INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nurture_next_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '3 days'),
  ADD COLUMN IF NOT EXISTS nurture_paused BOOLEAN DEFAULT FALSE;

ALTER TABLE website_leads 
  ADD COLUMN IF NOT EXISTS sector TEXT DEFAULT 'generic';
